services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: chainsaw
      POSTGRES_PASSWORD: chainsaw
      POSTGRES_DB: chainsaw
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data:
