services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: chainsaw
      POSTGRES_PASSWORD: chainsaw
      POSTGRES_DB: chainsaw
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./server/openapi.yaml:/openapi/openapi.yaml:ro

volumes:
  pg_data: