name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: "--deny warnings --warn unreachable-pub"

jobs:
  server:
    name: Server Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - name: Load Rust/Cargo Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all-targets --all-features --locked
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Test
        run: cargo test --all-targets --all-features --locked
  server-formatting:
    name: Server Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - name: Check Formatting
        run: cargo fmt -- --check

  client:
    name: Client Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          package_json_file: ./client/package.json
          run_install: false
      - uses: actions/setup-node@v7
        name: Install Node.js
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
          cache-dependency-path: ./client/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./client
      - name: Format
        run: pnpm run check
        working-directory: ./client
      - name: Lint
        run: pnpm run lint
        working-directory: ./client
      - name: Build
        run: pnpm run build
        working-directory: ./client
